import {Inter} from 'next/font/google';

import '../globals.css';

import NextAuthProvider from '@/providers/NextAuthProvider';
import Header from '@/components/header/Header';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Header />
          <main className="mt-4">{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
