import {Inter} from 'next/font/google';

import '../globals.css';

import NextAuthProvider from '@/providers/NextAuthProvider';
import Header from '@/components/header/Header';
import AuthTokenHandler from '@/lib/AuthTokenHandler';
import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <NextAuthProvider>
            <AuthTokenHandler>
              <Header />
              <main className="mt-4">{children}</main>
            </AuthTokenHandler>
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
