import {Inter} from 'next/font/google';

import '../globals.css';

import NextAuthProvider from '@/providers/NextAuthProvider';
import Header from '@/components/header/Header';
import AuthTokenSetup from '@/components/AuthTokenSetup';
import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <NextAuthProvider>
            <AuthTokenSetup>
              <Header />
              <main className="mt-4">{children}</main>
            </AuthTokenSetup>
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
