import '../globals.css';
import {Inter} from 'next/font/google';

import AuthTokenHandler from '@/lib/AuthTokenHandler';
import NextAuthProvider from '@/providers/NextAuthProvider';
import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';

import Header from '@/components/admin/Header/Header';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <NextAuthProvider>
            <AuthTokenHandler>
              <Header />
              <main>{children}</main>
            </AuthTokenHandler>
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
