import '../globals.css';
import {Inter} from 'next/font/google';

import Header from '@/components/header/Header';
import NextAuthProvider from '@/providers/NextAuthProvider';
import AuthSessionSetup from '@/components/AuthSessionSetup';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <AuthSessionSetup />
          <Header />
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
