import '../globals.css';
import {Inter} from 'next/font/google';

import Header from '@/components/header/Header';
import AuthTokenSetup from '@/components/AuthTokenSetup';
import NextAuthProvider from '@/providers/NextAuthProvider';
import ReactQueryClientProvider from '@/providers/ReactQueryClientProvider';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <NextAuthProvider>
            {/* <AuthTokenSetup> */}
            <Header />
            <main>{children}</main>
            {/* </AuthTokenSetup> */}
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
